# @package _global_

# Postive Grid
dset:
  wav: /home/yuehpo/coding/PositiveGrid/demucs_data
  samplerate: 44100
  channels: 1
  sources: ['clean', 'fx']
  use_musdb: False
  normalize: true


  

epochs: 320
batch_size: 8
model: htdemucs
weights: [1., 0.]  # weights over each source for the training/valid loss.
